# ** Section - A **​ Output Prediction
### A1. Array operations and vectorization​

import numpy as np​

import pandas as pd​

arr = np.array([10, 20, 30])
​
s = pd.Series([10, 20, 30])
​
print(arr * 2)​

print(s * 2)​

### A1.1. Predict the output of both statements.​

Output:[20 40 60]

0       20

1       40

2       60

dtype: int64


### A1.2. Identify one similarity and one difference between the two data structures.​

​Answer:

Both perform the multiplication on all values at once. The main difference is that Pandas Series also keeps an index for each value.

​

### A2. Boolean Filtering

import pandas as pd

df = pd.DataFrame({

'Student': ['A', 'B', 'C', 'D'],

'Marks': [45, 80, 65, 90]

})

result = df[df['Marks'] >= 65]

print(result[['Student', 'Marks']])

### A2.1 Predict the rows displayed.

Output:

  Student  Marks

1       B     80

2       C     65

3       D     90



### A2.2. How many rows and columns will the resulting DataFrame contain?

Answer:

Rows: 3

Columns: 2

Boolean filtering selects only the rows that satisfy a given condition. Here, students whose marks are greater than or equal to 65 are displayed.

### A3. Descriptive statistics​

import pandas as pd​

df = pd.DataFrame({​

'Marks': [10, 20, 30, 40, 50]​

})​

print(df['Marks'].mean())​

print(df['Marks'].max())​

print(df['Marks'].median())​

### A3.1. Predict all three outputs.​

Output:

30
50
30

### A3.2. Explain how the median differs from the mean.​

Answer:

10, 20, 30, 40, 50.     The middle value is 30, so the median is 30.

The mean is calculated by adding all values and dividing by the number of values, while the median is the middle value after sorting the data. The median is less affected by extreme values compared with the mean.



​

### A4. Group-wise Analysis​

import pandas as pd​

df = pd.DataFrame({​

'Department': ['IT', 'HR', 'IT', 'HR'],​

'Salary': [40000, 30000, 60000, 50000]​

})​

print(df.groupby('Department')['Salary'].mean())​

### A4.1. Predict the output.​

Output:

Department

HR    40000.0

IT    50000.0

Name: Salary, dtype: float64


### A4.2. Explain how groupby() calculates the department-wise average.​

Answer:

IT: 40,000 and 60,000 → average = 50,000

HR: 30,000 and 50,000 → average = 40,000

Then mean() calculates the average salary for each group.

groupby() divides the data into different departments, and mean() calculates the average salary separately for each department. This helps us compare the average salary of each group.



​

### A5.Pandas Correlation - Positive

import pandas as pd

df = pd.DataFrame({

'Hours': [1, 2, 3, 4],

'Marks': [20, 40, 60, 80]

})

print(df['Hours'].corr(df['Marks']))

### A5.1. Predict the correlation coefficient.

Output:

1.0

### A5.2. Interpret the direction and strength of the relationship.

Answer:

The correlation is 1.0, which shows a perfect positive relationship between study hours and marks.

In this data, when the study hours increase, the marks also increase.

### A6. Pandas Correlation - Negative​

import pandas as pd​

df = pd.DataFrame({​

'Price': [10, 20, 30, 40],​

'Demand': [100, 80, 60, 40]​

})​

print(df['Price'].corr(df['Demand']))​

### A6.1. Predict the correlation coefficient.​

Output:

-1.0

### A6.2. Explain what the sign of the coefficient indicates about the relationship.​

Answer:

The correlation coefficient is -1.0, which shows a perfect negative relationship. 

This means that when the price increases, the demand decreases proportionally.


​

# ** Section - B ** Code Correction

### Q. JSON and CSV

import pandas as pd

df = pd.read_csv("students.csv", header=None)

print(df)

### B1. A CSV file contains a header row, but the code uses `header=None`, so pandas treats that header row as data. Correct the code to use the first row as column names.

### Corrected code

import pandas as pd

df = pd.read_csv("students.csv", header=0)

print(df)

### Explonation:

Since the CSV file already contains a header row, we should read it as the column names. 

header=0 tells Pandas to use the first row as the header.

# B2. Data Analysis​

import pandas as pd​

df = pd.DataFrame({​

'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],​

'Salary': [30000, 50000, 25000, 60000, 45000, 70000]​

})​

print(df.sort_values('Salary').head(5)) ​

### Q.The objective is to display the five highest salaries from a DataFrame. Correct the code.​

In [24]:
#Corrected code
import pandas as pd
df = pd.DataFrame({'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
                   'Salary': [30000, 50000, 25000, 60000, 45000, 70000]})
print(df.sort_values('Salary', ascending=False).head(5))

  Employee  Salary
5        F   70000
3        D   60000
1        B   50000
4        E   45000
0        A   30000

### Explonation:

The original code sorted salaries from lowest to highest. 

I changed ascending=False so the highest salaries come first, and head(5) then selects the top five employees.

# B3. Cleaning Data ​

import pandas as pd​

df = pd.DataFrame({'Marks': [70, None, 90]})​

df['Marks'].fillna(df['Marks'].mean())​

print(df) ​

### Q.A student wants to replace missing marks with the column's mean but writes code that does not update the DataFrame. Correct the code

In [25]:
# Corrected code
import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

print(df)

   Marks
0   70.0
1   80.0
2   90.0

### Explonation:

fillna() creates the filled values, but the original code did not save those values back into the DataFrame. Assigning the result to df['Marks'] updates the column.

# B4. Correlation

import pandas as pd

df = pd.DataFrame({

'Hours': [1, 2, 3, 4],

'Marks': [20, 40, 60, 80]

})

print(df.corr('Hours', 'Marks'))

### Q. The objective is to calculate the correlation between Hours and Marks. Correct the code.

In [26]:
# Corrected code
import pandas as pd

df = pd.DataFrame({'Hours': [1, 2, 3, 4], 'Marks': [20, 40, 60, 80]})
print(df['Hours'].corr(df['Marks']))

1.0

### Explonation:

The original code used corr() incorrectly. We select the Hours and Marks columns and use .corr() between them to calculate their correlation. The result is 1.0, which shows a perfect positive relationship.

# SECTION - C: Edge Cases

### C1. Two NumPy arrays have shapes (3, 1) and (1, 3). Predict the shape of their element-wise sum and explain how broadcasting works. Why might the result differ from adding two one-dimensional arrays?

import numpy as np

a = np.array([[10], [20], [30]])

b = np.array([[1, 2, 3]])

result = a + b

print(result)

print(result.shape)

### C1.1. Predict the output of the given code.

### Output:

[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)

### C1.2. Identify the shapes of arrays a and b before addition.

Answer:

a has shape (3, 1).

b has shape (1, 3).

### C1.3. Explain how NumPy broadcasting enables the addition of these arrays.

Answer:

NumPy compares dimensions from right to left. Dimensions are compatible when they are equal or one of them is 1. Here, the (3, 1) and (1, 3) arrays broadcast to shape (3, 3), producing the stated result without requiring manually created copies.

### C1.4. What would happen if b were replaced with np.array([1, 2])? Explain the reason.

Answer:

The addition works. The one-dimensional array has shape (2,), which aligns with (3, 1) as if it had shape (1, 2). The dimensions are compatible, so the result has shape (3, 2):

[[11 12]
 [21 22]
 [31 32]]

### C2. A CSV file contains commas inside quoted text fields, missing values, and dates in different formats. Explain how incorrect parsing can affect the resulting DataFrame and identify suitable read options or preprocessing steps.

Given dataset: students.csv

ID,Name,Date,Marks

101,"Asha, R",2026-09-01,80

102,Ravi,01/09/2026,

103,Neha,2026-09-03,NA

Given code:

import pandas as pd

df = pd.read_csv("students.csv")

print(df)

print(df.dtypes)

#### C2.1. Predict how the quoted comma in "Asha, R" will be handled when the CSV file is read.

Answer:

Pandas correctly handles the comma inside "Asha, R" because the value is enclosed in double quotes. It treats Asha, R as one Name value, not as two separate columns.

#### C2.2. Identify the potential issues with the Date and Marks columns.

Answer:

The dates use different formats, and 01/09/2026 is ambiguous unless the day/month order is known. Convert the column explicitly using the expected date convention.

By default, read_csv treats the text "NA" as a missing value. If its meaning needs to be investigated, read the file with keep_default_na=False so the literal text is preserved. The blank Marks value should also be handled as missing.

#### C2.3. Rewrite the code to handle missing marks and convert the date column into a suitable date-time format.

import pandas as pd

df = pd.read_csv("students.csv", keep_default_na=False, na_values=[""])

df["Marks_raw"] = df["Marks"]

df["Date"] = pd.to_datetime(df["Date"], format="mixed", dayfirst=True, errors="coerce")

### Corrected Code:

df["Marks"] = df["Marks"].replace("NA", pd.NA)

df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")

df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

print(df)

print(df.dtypes)

### Explanation:

keep_default_na=False preserves the literal "NA" for inspection, while na_values=[""] reads blank fields as missing. The raw Marks value is retained in Marks_raw. After confirming the meaning of "NA", to_numeric converts marks to numbers and the missing values are filled with the mean. format="mixed" supports the different date formats in pandas 2.0 and later; dayfirst=True interprets 01/09/2026 as 1 September 2026.

#### C2.4. Explain why the value "NA" should be investigated before deciding whether it represents a missing value.​
### Explonation:

"NA" should be investigated before treating it as a missing value because it may have a specific meaning in the dataset, such as absent or not applicable. Automatically converting it to a missing value could result in loss of useful information.

​

### Q3. A salary column contains the values 25000, 30000, 35000, and 10000000. Explain how the extreme value affects the mean compared with the median. Identify which statistic may better represent a typical employee's salary and justify your choice.​

Given code:​

import pandas as pd​

df = pd.DataFrame({​

"Employee": ["A", "B", "C", "D"],​

"Salary": [25000, 30000, 35000, 10000000]​

})​

print("Mean:", df["Salary"].mean())​

print("Median:", df["Salary"].median())​

​

### C3.1. Predict the mean and median salary.​

Answer:

Mean: 2522500.0

Median: 32500.0



### C3.2. Identify the effect of the extreme salary on the mean.​

#### Explonatioin:

The 10,000,000 salary is an extreme value, so it pulls the mean much higher.

Without that extreme value, the other salaries are only between 25,000 and 35,000, but the mean becomes 2,522,500 because of the 10,000,000 salary.

The median is affected much less by this extreme value.

### C3.3. Which statistic may better represent a typical employee's salary in this dataset? Justify your answer.​

Answer:

The median may better represent a typical employee's salary in this dataset.

Reason: The median is less affected by extreme values. Here, the median is 32,500, which is much closer to the salaries of employees A, B, and C.

In [27]:
import pandas as pd

df = pd.DataFrame({"Employee": ["A", "B", "C", "D"],"Salary": [25000, 30000, 35000, 10000000]})
print("Mean:", df["Salary"].mean())
print("Median:", df["Salary"].median())

Mean: 2522500.0
Median: 32500.0

### C3.4. code to identify the employee record with the highest salary and explain why the record should be investigated before removing it​

In [28]:
highest_salary = df.loc[df["Salary"].idxmax()]

print(highest_salary)

Employee           D
Salary      10000000
Name: 3, dtype: object

### Explonation:

The extreme salary of 10,000,000 increases the mean to 2,522,500, while the median is only 32,500. Therefore, the median better represents a typical salary because it is less affected by extreme values. The highest salary record should be investigated before removing it because it may be a genuine value or a data entry error.

# ** SECTION - D ** Scenario-based Questions​

### Q. A student assessment dataset contains missing marks, duplicate student records, inconsistent department names such as IT, it, and I.T., and marks stored as text. Develop a cleaning sequence to standardize the data, handle missing values, remove duplicates, and convert marks into a suitable numeric type. State one risk of deleting missing values without investigating why they are missing. ​

### D1.1. Load the CSV file and inspect the dataset using head(), info(), and isnull().sum().​

In [ ]:
import pandas as pd

df = pd.read_csv(r"C:\Users\ADMIN\OneDrive\Documents\Jupyter_file\student_assessment_dirty.csv")
print(df)

   Student_ID Student_Name Department Assessment     Marks
0        S101         Asha         IT     Python        85
1        S102         Ravi         it     Python        78
2        S103         Neha       I.T.     Python        92
3        S104        Karan         HR     Python       NaN
4        S105        Meera         HR     Python    Absent
5        S106        Arjun    Finance     Python         0
6        S107        Priya    finance     Python        67
7        S108        Rahul         IT     Python        75
8        S102         Ravi         it     Python        78
9        S109        Sneha       I.T.     Python       NaN
10       S110        Varun         HR     Python  88 marks
11       S111         Diya    Finance     Python        91
12       S112         Aman         IT     Python       NaN
13       S113        Nisha         HR     Python        64
14       S114        Kabir    Finance     Python       105

In [ ]:
import pandas as pd

df = pd.read_csv(r"C:\Users\ADMIN\OneDrive\Documents\Jupyter_file\student_assessment_dirty.csv",keep_default_na=False,)
df = df.replace(r"^\s*$", pd.NA, regex=True)

print("First 5 rows:")
display(df.head())
print("\nDataset information:")
df.info()
print("\nMissing values:")
print(df.isnull().sum())

First 5 rows:

  Student_ID Student_Name Department Assessment   Marks
0       S101         Asha         IT     Python      85
1       S102         Ravi         it     Python      78
2       S103         Neha       I.T.     Python      92
3       S104        Karan         HR     Python     NaN
4       S105        Meera         HR     Python  Absent

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    15 non-null     str
 1   Student_Name  15 non-null     str
 2   Department    15 non-null     str
 3   Assessment    15 non-null     str
 4   Marks         13 non-null     str
dtypes: str(5)
memory usage: 732.0 bytes

Missing values:
Student_ID      0
Student_Name    0
Department      0
Assessment      0
Marks           2
dtype: int64

### Explonation:

First, I load the CSV file and inspect the first few rows, column information, and missing values. This helps me understand the problems in the dataset before cleaning it.

### D1.2. Standardize department names so that IT, it, and I.T. are represented consistently. Apply the same approach to Finance.​

Our data contains:

IT

it

I.T.

Finance

finance

In [31]:
df["Department"] = df["Department"].str.strip()

df["Department"] = df["Department"].replace({"it": "IT","I.T.": "IT","finance": "Finance"})
print(df["Department"].value_counts())

Department
IT         7
HR         4
Finance    4
Name: count, dtype: int64

Now:

IT
Finance
HR

### Explanation:

I standardize the department names so that different forms such as IT, it, and I.T. are treated as the same department. I also make Finance consistent.

### D1.3. Identify and remove exact duplicate student assessment records.​

In [32]:
duplicates_removed = int(df.duplicated().sum())
print("Duplicate records:", duplicates_removed)

Duplicate records: 1

In [33]:
df = df.drop_duplicates()

print("Records after removing duplicates:", len(df))

Records after removing duplicates: 14

### Explonation:

The record for S102 Ravi appears twice with exactly the same information. I remove the duplicate because it represents the same student assessment record.

### D1.4. Convert the Marks column into a numeric format, handling "88 marks", "Absent", "NA", and blank entries appropriately.​

In [34]:
df["Marks_raw"] = df["Marks"].astype("string")
df["Marks"] = df["Marks_raw"].str.extract(r"(-?\d+(?:\.\d+)?)")[0]
df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")

In [35]:
display(df[["Student_ID", "Student_Name", "Marks_raw", "Marks"]])

   Student_ID Student_Name Marks_raw  Marks
0        S101         Asha        85     85
1        S102         Ravi        78     78
2        S103         Neha        92     92
3        S104        Karan      <NA>   <NA>
4        S105        Meera    Absent   <NA>
5        S106        Arjun         0      0
6        S107        Priya        67     67
7        S108        Rahul        75     75
9        S109        Sneha        NA   <NA>
10       S110        Varun  88 marks     88
11       S111         Diya        91     91
12       S112         Aman      <NA>   <NA>
13       S113        Nisha        64     64
14       S114        Kabir       105    105

### Explonation:

converted the Marks column into numeric values. The value 88 marks is converted to 88. Values such as Absent, NA, and blank entries do not contain a valid number, so they become missing values.

### D1.5.  Investigate missing marks and distinguish absent students from students whose marks have not been entered. State one risk of deleting missing values without investigating why they are missing.​

In [36]:
df["Mark_Status"] = "Available"

df.loc[df["Marks_raw"].str.lower() == "absent","Mark_Status"] = "Absent"
df.loc[df["Marks"].isna() &(df["Mark_Status"] != "Absent"),"Mark_Status"] = "Not Entered / NA"
display(df[["Student_ID","Student_Name","Marks_raw","Marks","Mark_Status"]])

   Student_ID Student_Name Marks_raw  Marks       Mark_Status
0        S101         Asha        85     85         Available
1        S102         Ravi        78     78         Available
2        S103         Neha        92     92         Available
3        S104        Karan      <NA>   <NA>  Not Entered / NA
4        S105        Meera    Absent   <NA>            Absent
5        S106        Arjun         0      0         Available
6        S107        Priya        67     67         Available
7        S108        Rahul        75     75         Available
9        S109        Sneha        NA   <NA>  Not Entered / NA
10       S110        Varun  88 marks     88         Available
11       S111         Diya        91     91         Available
12       S112         Aman      <NA>   <NA>  Not Entered / NA
13       S113        Nisha        64     64         Available
14       S114        Kabir       105    105         Available

### Explanation:

I investigate the missing marks instead of deleting the records immediately. Absent means the student was absent, while blank or NA may mean that the mark was not entered or is unavailable. Deleting missing records without investigating can bias the analysis if the missingness is related to attendance or student performance.

### D1.6. Identify marks outside the valid range of 0–100 and decide how they should be handled.​

In [37]:
invalid_mask = (df["Marks"] < 0) | (df["Marks"] > 100)
invalid_marks = df.loc[invalid_mask].copy()

print("Invalid marks:")
display(invalid_marks[["Student_ID", "Student_Name", "Marks"]])

df.loc[invalid_mask, "Mark_Status"] = "Invalid"
df.loc[invalid_mask, "Marks"] = pd.NA

Invalid marks:

   Student_ID Student_Name  Marks
14       S114        Kabir    105

### Explanation:

I check whether the marks are between 0 and 100. A value outside this range is flagged as Invalid and its numeric value is set to missing until it can be investigated. I keep the original record and report how many invalid marks were identified.

### D1.7. Display the cleaned DataFrame and report the number of records removed, missing marks remaining, and invalid marks identified.​

In [38]:
records_removed = duplicates_removed
print("Records removed:", records_removed)

Records removed: 1

In [ ]:
print("Cleaned DataFrame:")
display(df)
print("Records removed:", records_removed)
missing_mark_count = df["Marks"].isna().sum()
print("Missing marks remaining:", missing_mark_count)
print("Invalid marks identified:", len(invalid_marks))

Cleaned DataFrame:

,Student_ID,Student_Name,Department,Assessment,Marks,Marks_raw,Mark_Status
0,S101,Asha,IT,Python,85,85,Available
1,S102,Ravi,IT,Python,78,78,Available
2,S103,Neha,IT,Python,92,92,Available
3,S104,Karan,HR,Python,<NA>,<NA>,Not Entered / NA
4,S105,Meera,HR,Python,<NA>,Absent,Absent
5,S106,Arjun,Finance,Python,0,0,Available
6,S107,Priya,Finance,Python,67,67,Available
7,S108,Rahul,IT,Python,75,75,Available
9,S109,Sneha,IT,Python,<NA>,NA,Not Entered / NA
10,S110,Varun,HR,Python,88,88 marks,Available
11,S111,Diya,Finance,Python,91,91,Available
12,S112,Aman,IT,Python,<NA>,<NA>,Not Entered / NA
13,S113,Nisha,HR,Python,64,64,Available
14,S114,Kabir,Finance,Python,<NA>,105,Invalid

Records removed: 1
Missing marks remaining: 5
Invalid marks identified: 1

### Explanation:

In this step, I display the final cleaned DataFrame to check the changes made to the data. I also report how many duplicate records were removed, how many missing marks are still present, and how many invalid marks were identified. This helps me verify that the data cleaning process was completed correctly.